name: Environmental Variable Demo

on: [push]

env:
  GREETING: "Hello"

jobs:
  print-greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Print Greeting
      run: echo "${{ env.GREETING }}, World!"


